<a href="https://colab.research.google.com/github/DiegoMauricioSuaza/ActividadUno/blob/main/EVIDENCIA_DE_APRENDIZAJE_1_AN%C3%81LISIS_EXPLORATORIO_DE_DATOS_DEL_COVID_19_EN_COLOMBIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EVIDENCIA DE APRENDIZAJE 1. ANÁLISIS EXPLORATORIO DE DATOS DEL COVID-19 EN COLOMBIA

DIEGO MAURICIO SUAZA HOLGUÍN

ANALÍTICA DE DATOS PARA INGENIERÍA SOFTWARE Y DATOS (CAROLINA MARQUEZ) - PREICA2602B010191

INGENIERIA DE SOFTWARE DE DATOS

UNIVERSIDAD DIGITAL DE ANTIOQUIA

25 de agosto de 2026 Medellín, Antioquia

EJERCICIO 1

1- Importar las librerías

NumPy: permite trabajar con operaciones numéricas y arreglos.

Pandas: permite cargar, organizar, analizar y transformar los datos.

Matplotlib: permite realizar gráficos y visualizaciones.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

2- Cargar los datos

In [2]:
from google.colab import files
uploaded = files.upload ()

Saving Casos_positivos_de_COVID-19_en_Colombia.csv to Casos_positivos_de_COVID-19_en_Colombia.csv

In [3]:
# Cargar el dataset

data = pd.read_csv('Casos_positivos_de_COVID-19_en_Colombia.csv')
data.head()

/tmp/ipykernel_4830/1341297126.py:3: DtypeWarning: Columns (13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('Casos_positivos_de_COVID-19_en_Colombia.csv')

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
0,2020-12-24 00:00:00,"1,556,979",2020-12-22 00:00:00,76,VALLE,"76,001",CALI,67,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6.0,NaN
1,2020-12-24 00:00:00,"1,556,980",2020-12-19 00:00:00,76,VALLE,"76,001",CALI,66,1,F,...,NaN,NaN,Recuperado,2020-12-07 00:00:00,NaN,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6.0,NaN
2,2020-12-24 00:00:00,"1,556,981",2020-12-19 00:00:00,76,VALLE,"76,001",CALI,68,1,F,...,NaN,NaN,Recuperado,2020-12-18 00:00:00,NaN,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6.0,NaN
3,2020-12-24 00:00:00,"1,556,982",2020-12-22 00:00:00,76,VALLE,"76,001",CALI,74,1,F,...,NaN,NaN,Fallecido,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN,NaN,6.0,NaN
4,2020-12-24 00:00:00,"1,556,983",2020-12-22 00:00:00,76,VALLE,"76,001",CALI,65,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6.0,NaN

3- Obtén la información estructural del DataFrame con el método .info(), y describe los resultados

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6390971 entries, 0 to 6390970
Data columns (total 23 columns):
 #   Column                        Dtype
---  ------                        -----
 0   fecha reporte web             object
 1   ID de caso                    object
 2   Fecha de notificación         object
 3   Código DIVIPOLA departamento  object
 4   Nombre departamento           object
 5   Código DIVIPOLA municipio     object
 6   Nombre municipio              object
 7   Edad                          int64
 8   Unidad de medida de edad      int64
 9   Sexo                          object
 10  Tipo de contagio              object
 11  Ubicación del caso            object
 12  Estado                        object
 13  Código ISO del país           object
 14  Nombre del país               object
 15  Recuperado                    object
 16  Fecha de inicio de síntomas   object
 17  Fecha de muerte               object
 18  Fecha de diagnóstico          object
 19  Fecha de recuperación         object
 20  Tipo de recuperación          object
 21  Pertenencia étnica            float64
 22  Nombre del grupo étnico       object
dtypes: float64(1), int64(2), object(20)
memory usage: 1.1+ GB

In [5]:
data.dtypes

fecha reporte web                object
ID de caso                       object
Fecha de notificación            object
Código DIVIPOLA departamento     object
Nombre departamento              object
Código DIVIPOLA municipio        object
Nombre municipio                 object
Edad                              int64
Unidad de medida de edad          int64
Sexo                             object
Tipo de contagio                 object
Ubicación del caso               object
Estado                           object
Código ISO del país              object
Nombre del país                  object
Recuperado                       object
Fecha de inicio de síntomas      object
Fecha de muerte                  object
Fecha de diagnóstico             object
Fecha de recuperación            object
Tipo de recuperación             object
Pertenencia étnica              float64
Nombre del grupo étnico          object
dtype: object

In [6]:
print("Número de filas:", data.shape[0])
print("Número de columnas:", data.shape[1])

Número de filas: 6390971
Número de columnas: 23

4- Visualizar la estructura del DataFrame

.head()

In [7]:
data.head()

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
0,2020-12-24 00:00:00,"1,556,979",2020-12-22 00:00:00,76,VALLE,"76,001",CALI,67,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6.0,NaN
1,2020-12-24 00:00:00,"1,556,980",2020-12-19 00:00:00,76,VALLE,"76,001",CALI,66,1,F,...,NaN,NaN,Recuperado,2020-12-07 00:00:00,NaN,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6.0,NaN
2,2020-12-24 00:00:00,"1,556,981",2020-12-19 00:00:00,76,VALLE,"76,001",CALI,68,1,F,...,NaN,NaN,Recuperado,2020-12-18 00:00:00,NaN,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6.0,NaN
3,2020-12-24 00:00:00,"1,556,982",2020-12-22 00:00:00,76,VALLE,"76,001",CALI,74,1,F,...,NaN,NaN,Fallecido,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN,NaN,6.0,NaN
4,2020-12-24 00:00:00,"1,556,983",2020-12-22 00:00:00,76,VALLE,"76,001",CALI,65,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6.0,NaN

.tail()

In [8]:
data.tail()

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
6390966,2021-10-24 00:00:00,"4,990,088",2021-10-19 00:00:00,76,VALLE,"76,520",PALMIRA,37,1,M,...,NaN,NaN,Recuperado,2021-10-13 00:00:00,NaN,2021-10-23 00:00:00,2021-10-27 00:00:00,Tiempo,6.0,NaN
6390967,2021-10-24 00:00:00,"4,990,091",2021-10-23 00:00:00,76,VALLE,"76,520",PALMIRA,36,1,M,...,NaN,NaN,Recuperado,2021-10-16 00:00:00,NaN,2021-10-23 00:00:00,2021-10-30 00:00:00,Tiempo,6.0,NaN
6390968,2021-10-24 00:00:00,"4,990,092",2021-10-19 00:00:00,76,VALLE,"76,364",JAMUNDI,39,1,F,...,NaN,NaN,Recuperado,2021-10-18 00:00:00,NaN,2021-10-23 00:00:00,2021-11-01 00:00:00,Tiempo,6.0,NaN
6390969,2021-10-24 00:00:00,"4,990,095",2021-11-05 00:00:00,76,VALLE,"76,364",JAMUNDI,43,1,F,...,NaN,NaN,Recuperado,2021-10-21 00:00:00,NaN,2021-10-23 00:00:00,2021-11-04 00:00:00,PCR,6.0,NaN
6390970,2021-10-24 00:00:00,"4,990,096",2021-10-22 00:00:00,76,VALLE,"76,364",JAMUNDI,16,1,M,...,NaN,NaN,Recuperado,2021-10-21 00:00:00,NaN,2021-10-23 00:00:00,2021-11-04 00:00:00,PCR,6.0,NaN

.sample()

In [9]:
data.sample(5)

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
71967,2020-09-13 00:00:00,"710,190",2020-09-05 00:00:00,88,SAN ANDRES,"88,001",SAN ANDRES,57,1,M,...,NaN,NaN,Recuperado,2020-08-21 00:00:00,NaN,2020-09-12 00:00:00,2020-09-14 00:00:00,Tiempo,5.0,NaN
576884,2021-04-15 00:00:00,"2,587,634",2021-04-12 00:00:00,11,BOGOTA,"11,001",BOGOTA,31,1,F,...,NaN,NaN,Recuperado,2021-04-12 00:00:00,NaN,2021-04-13 00:00:00,2021-04-26 00:00:00,Tiempo,6.0,NaN
416568,2021-06-01 00:00:00,"3,425,072",2021-05-29 00:00:00,5,ANTIOQUIA,"5,615",RIONEGRO,17,1,F,...,NaN,NaN,Recuperado,2021-05-25 00:00:00,NaN,2021-05-29 00:00:00,2021-06-08 00:00:00,Tiempo,6.0,NaN
3869400,2021-06-14 00:00:00,"3,775,286",2021-05-30 00:00:00,8,ATLANTICO,"8,638",SABANALARGA,44,1,M,...,NaN,NaN,Recuperado,2021-05-28 00:00:00,NaN,2021-06-10 00:00:00,2021-06-15 00:00:00,PCR,6.0,NaN
3933924,2021-06-10 00:00:00,"3,656,559",2021-06-01 00:00:00,11,BOGOTA,"11,001",BOGOTA,48,1,F,...,NaN,NaN,Recuperado,NaN,NaN,2021-06-07 00:00:00,2021-06-15 00:00:00,Tiempo,6.0,NaN

Para obtener 10 registros aleatorios

In [10]:
data.sample(10, random_state=42)

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
1843699,2020-08-01 00:00:00,"299,426",2020-07-17 00:00:00,5,ANTIOQUIA,"5,045",APARTADO,8,1,F,...,NaN,NaN,Recuperado,2020-07-10 00:00:00,NaN,2020-07-31 00:00:00,2020-08-09 00:00:00,Tiempo,6.0,NaN
1466457,2020-09-24 00:00:00,"785,377",2020-09-21 00:00:00,76,VALLE,"76,001",CALI,18,1,M,...,NaN,NaN,Recuperado,2020-09-20 00:00:00,NaN,2020-09-23 00:00:00,2020-10-08 00:00:00,Tiempo,6.0,NaN
1519025,2020-12-31 00:00:00,"1,635,976",2020-12-28 00:00:00,11,BOGOTA,"11,001",BOGOTA,56,1,F,...,NaN,NaN,Recuperado,NaN,NaN,2020-12-29 00:00:00,2021-01-12 00:00:00,Tiempo,6.0,NaN
5211106,2021-10-23 00:00:00,"4,988,645",2021-10-21 00:00:00,54,NORTE SANTANDER,"54,001",CUCUTA,50,1,M,...,NaN,NaN,Recuperado,2021-10-11 00:00:00,NaN,2021-10-20 00:00:00,2021-10-25 00:00:00,Tiempo,6.0,NaN
2515565,2021-01-15 00:00:00,"1,866,131",2021-01-09 00:00:00,11,BOGOTA,"11,001",BOGOTA,51,1,F,...,NaN,NaN,Recuperado,2021-01-09 00:00:00,NaN,2021-01-14 00:00:00,2021-01-25 00:00:00,PCR,6.0,NaN
6115468,2022-01-20 00:00:00,"5,648,668",2022-01-18 00:00:00,"8,001",BARRANQUILLA,"8,001",BARRANQUILLA,62,1,M,...,NaN,NaN,Recuperado,2022-01-14 00:00:00,NaN,2022-01-18 00:00:00,2022-01-26 00:00:00,Tiempo,6.0,NaN
2938805,2021-01-12 00:00:00,"1,810,213",2021-01-09 00:00:00,54,NORTE SANTANDER,"54,313",GRAMALOTE,74,1,M,...,NaN,NaN,Fallecido,2021-01-05 00:00:00,2021-01-09 00:00:00,2021-01-09 00:00:00,NaN,NaN,6.0,NaN
2562023,2021-01-15 00:00:00,"1,858,301",2021-01-10 00:00:00,5,ANTIOQUIA,"5,001",MEDELLIN,22,1,F,...,NaN,NaN,Recuperado,2021-01-09 00:00:00,NaN,2021-01-13 00:00:00,2021-01-23 00:00:00,Tiempo,6.0,NaN
3585416,2021-07-13 00:00:00,"4,536,160",2021-07-07 00:00:00,23,CORDOBA,"23,686",SAN PELAYO,24,1,F,...,NaN,NaN,Recuperado,2021-07-07 00:00:00,NaN,2021-07-11 00:00:00,2021-07-22 00:00:00,PCR,6.0,NaN
2040244,2020-07-30 00:00:00,"276,611",2020-07-23 00:00:00,"47,001",STA MARTA D.E.,"47,001",SANTA MARTA,27,1,F,...,NaN,NaN,Recuperado,2020-07-19 00:00:00,NaN,2020-07-29 00:00:00,2020-08-16 00:00:00,Tiempo,6.0,NaN

5- Utiliza value_counts(dropna=False), para visualizar las siguientes variables: Estado, Atención, Sexo, Tipo, País_procedencia, Tipo_recuperación, Pertenencia_étnica, Nombre_grupo_étnico

value_counts(dropna=False)

In [11]:
columns_to_analyze = [
 'Estado',
 'Ubicación del caso',
 'Sexo',
 'Tipo de contagio',
 'Nombre del país',
 'Tipo de recuperación',
 'Pertenencia étnica',
 'Nombre del grupo étnico'
]

for col in columns_to_analyze:
 if col in data.columns:
    print(data[col].value_counts(dropna=False))
 else:
    print(f"\n--- Column '{col}' not found in DataFrame ---")

Estado
Leve         6154791
Fallecido     143125
leve           50623
NaN            41268
Moderado        1056
Grave            106
LEVE               2
Name: count, dtype: int64
Ubicación del caso
Casa            6177081
Fallecido        143125
NaN               41268
casa              28328
Hospital           1056
Hospital UCI        106
CASA                  7
Name: count, dtype: int64
Sexo
F    3417087
M    2973872
f          6
m          6
Name: count, dtype: int64
Tipo de contagio
Comunitaria    4447740
Relacionado    1939528
Importado         3703
Name: count, dtype: int64
Nombre del país
NaN                            6387253
ESTADOS UNIDOS DE AMÉRICA         1418
MÉXICO                             385
ESPAÑA                             370
BRASIL                             285
                                ...
SAN BARTOLOMÉ                        1
VENEUELA                             1
REPUBLICA POPULAR DEL CONGO          1
REPÚBLICA CHECA                      1
HAITÍ                                1
Name: count, Length: 90, dtype: int64
Tipo de recuperación
Tiempo    5274348
PCR        933773
NaN        182398
TIEMPO        452
Name: count, dtype: int64
Pertenencia étnica
6.0    6166659
5.0     137411
1.0      84202
NaN       2156
3.0        405
2.0        138
Name: count, dtype: int64
Nombre del grupo étnico
NaN                            6307107
Por definir                      17222
Sin Comunidad                    12064
ZENU                              9264
PIJAO                             4112
                                ...
MESAS DE SAN JUAN                    1
YORROLOKI                            1
GEMEMAHS-KURAPULEN-JUYUMANA          1
ISHORSHIMANA                         1
TUTCHONKAT                           1
Name: count, Length: 1888, dtype: int64

EJERCICIO 2

Análisis Descriptivo de Datos (ADD)

1- Realiza un análisis descriptivo de datos para todas las variables

In [12]:
# Valores faltantes por variable
faltantes = data.isnull().sum()

print(faltantes)

fecha reporte web                     0
ID de caso                            0
Fecha de notificación                 0
Código DIVIPOLA departamento          0
Nombre departamento                   0
Código DIVIPOLA municipio             0
Nombre municipio                      0
Edad                                  0
Unidad de medida de edad              0
Sexo                                  0
Tipo de contagio                      0
Ubicación del caso                41268
Estado                            41268
Código ISO del país             6387261
Nombre del país                 6387253
Recuperado                        36327
Fecha de inicio de síntomas      505384
Fecha de muerte                 6206578
Fecha de diagnóstico               2755
Fecha de recuperación            182324
Tipo de recuperación             182398
Pertenencia étnica                 2156
Nombre del grupo étnico         6307107
dtype: int64

In [ ]:
valores_unicos = pd.DataFrame({
    'Variable': data.columns,
    'Valores únicos': [data[col].nunique(dropna=False) for col in data.columns]
})

valores_unicos

                        Variable  Valores únicos
0              fecha reporte web             872
1                     ID de caso         6390971
2          Fecha de notificación            1413
3   Código DIVIPOLA departamento              36
4            Nombre departamento              41
5      Código DIVIPOLA municipio            1121
6               Nombre municipio            1057
7                           Edad             114
8       Unidad de medida de edad               5
9                           Sexo               4
10              Tipo de contagio               3
11            Ubicación del caso               7
12                        Estado               7
13           Código ISO del país             122
14               Nombre del país              90
15                    Recuperado               5
16   Fecha de inicio de síntomas            1420
17               Fecha de muerte            1392
18          Fecha de diagnóstico            1411
19         Fecha de recuperación             970
20          Tipo de recuperación               4
21            Pertenencia étnica               6
22       Nombre del grupo étnico            1888

Análisis de la variable Edad

La variable Edad es cuantitativa discreta porque representa la edad de las personas en años. Su promedio permite conocer la edad media de los casos, mientras que la mediana permite identificar el valor central de la distribución.

La comparación entre promedio y mediana también puede ayudar a identificar si existen diferencias importantes en la distribución de las edades.

In [13]:
data['Edad'].describe()

print("Edad promedio:", data['Edad'].mean())
print("Edad mediana:", data['Edad'].median())
print("Edad mínima:", data['Edad'].min())
print("Edad máxima:", data['Edad'].max())

Edad promedio: 39.981712638032626
Edad mediana: 38.0
Edad mínima: 1
Edad máxima: 114

Análisis de variables categóricas

In [14]:
variables_categoricas = data.select_dtypes(
    include=['object', 'category']
).columns

print("Variables categóricas:")
print(variables_categoricas)

for columna in variables_categoricas:
    print("\n====================================")
    print("VARIABLE:", columna)
    print("====================================")
    print(data[columna].value_counts(dropna=False))

Variables categóricas:
Index(['fecha reporte web', 'ID de caso', 'Fecha de notificación',
       'Código DIVIPOLA departamento', 'Nombre departamento',
       'Código DIVIPOLA municipio', 'Nombre municipio', 'Sexo',
       'Tipo de contagio', 'Ubicación del caso', 'Estado',
       'Código ISO del país', 'Nombre del país', 'Recuperado',
       'Fecha de inicio de síntomas', 'Fecha de muerte',
       'Fecha de diagnóstico', 'Fecha de recuperación', 'Tipo de recuperación',
       'Nombre del grupo étnico'],
      dtype='object')

====================================
VARIABLE: fecha reporte web
====================================
fecha reporte web
2022-01-15 00:00:00    35576
2022-01-14 00:00:00    34924
2021-06-26 00:00:00    33593
2021-06-24 00:00:00    32997
2021-06-25 00:00:00    32732
                       ...
2020-03-11 00:00:00        6
2020-03-12 00:00:00        5
2020-03-13 00:00:00        5
2020-03-09 00:00:00        2
2020-03-06 00:00:00        1
Name: count, Length: 872, dtype: int64

====================================
VARIABLE: ID de caso
====================================
ID de caso
4,990,096    1
1,556,979    1
1,556,980    1
1,556,981    1
1,556,982    1
            ..
1,841,910    1
1,137,429    1
1,556,992    1
1,556,991    1
1,556,990    1
Name: count, Length: 6390971, dtype: int64

====================================
VARIABLE: Fecha de notificación
====================================
Fecha de notificación
2022-01-06 00:00:00    44424
2022-01-07 00:00:00    41706
2022-01-05 00:00:00    37292
2021-06-10 00:00:00    36880
2021-06-15 00:00:00    36602
                       ...
2020-03-08 00:00:00        2
2020-03-03 00:00:00        1
2020-03-07 00:00:00        1
2020-03-06 00:00:00        1
2020-03-02 00:00:00        1
Name: count, Length: 1413, dtype: int64

====================================
VARIABLE: Código DIVIPOLA departamento
====================================
Código DIVIPOLA departamento
11        1888137
5          955271
76         572724
25         331338
68         297532
8,001      277989
13,001     163526
8          141072
15         131133
73         127765
54         126015
23         123095
17         120030
66         110235
20         109830
52         108967
50         108194
41         103578
47,001      84863
19          77337
63          73290
70          67471
44          58353
85          43302
13          40336
47          33165
18          25750
86          22143
27          18907
81          17387
88          10402
91           7879
95           5692
99           3496
94           2795
97           1972
Name: count, dtype: int64

====================================
VARIABLE: Nombre departamento
====================================
Nombre departamento
BOGOTA             1888137
ANTIOQUIA           955271
VALLE               572724
CUNDINAMARCA        331331
SANTANDER           297370
BARRANQUILLA        277989
CARTAGENA           163526
ATLANTICO           141072
BOYACA              131133
TOLIMA              127764
NORTE SANTANDER     126015
CORDOBA             123095
CALDAS              120029
RISARALDA           110235
CESAR               109830
NARIÑO              108967
META                108194
HUILA               103578
STA MARTA D.E.       84863
CAUCA                77337
QUINDIO              73290
SUCRE                67471
GUAJIRA              58353
CASANARE             43302
BOLIVAR              40336
MAGDALENA            33165
CAQUETA              25750
PUTUMAYO             22142
CHOCO                18907
ARAUCA               17387
SAN ANDRES           10402
AMAZONAS              7879
GUAVIARE              5692
VICHADA               3496
GUAINIA               2795
VAUPES                1972
Santander              162
Cundinamarca             7
Caldas                   1
Tolima                   1
Putumayo                 1
Name: count, dtype: int64

====================================
VARIABLE: Código DIVIPOLA municipio
====================================
Código DIVIPOLA municipio
11,001    1888137
5,001      550794
76,001     406751
8,001      277989
13,001     163526
           ...
91,263          7
91,530          7
27,086          4
97,777          1
94,888          1
Name: count, Length: 1121, dtype: int64

====================================
VARIABLE: Nombre municipio
====================================
Nombre municipio
BOGOTA          1888137
MEDELLIN         550790
CALI             406751
BARRANQUILLA     277989
CARTAGENA        163526
                 ...
MEDELLiN              1
Anserma               1
Guepsa                1
Pensilvania           1
momil                 1
Name: count, Length: 1057, dtype: int64

====================================
VARIABLE: Sexo
====================================
Sexo
F    3417087
M    2973872
f          6
m          6
Name: count, dtype: int64

====================================
VARIABLE: Tipo de contagio
====================================
Tipo de contagio
Comunitaria    4447740
Relacionado    1939528
Importado         3703
Name: count, dtype: int64

====================================
VARIABLE: Ubicación del caso
====================================
Ubicación del caso
Casa            6177081
Fallecido        143125
NaN               41268
casa              28328
Hospital           1056
Hospital UCI        106
CASA                  7
Name: count, dtype: int64

====================================
VARIABLE: Estado
====================================
Estado
Leve         6154791
Fallecido     143125
leve           50623
NaN            41268
Moderado        1056
Grave            106
LEVE               2
Name: count, dtype: int64

====================================
VARIABLE: Código ISO del país
====================================
Código ISO del país
NaN      6387261
840.0       1369
484.0        370
724.0        357
76.0         268
          ...
422.0          1
652.0          1
178.0          1
203.0          1
332.0          1
Name: count, Length: 122, dtype: int64

====================================
VARIABLE: Nombre del país
====================================
Nombre del país
NaN                            6387253
ESTADOS UNIDOS DE AMÉRICA         1418
MÉXICO                             385
ESPAÑA                             370
BRASIL                             285
                                ...
SAN BARTOLOMÉ                        1
VENEUELA                             1
REPUBLICA POPULAR DEL CONGO          1
REPÚBLICA CHECA                      1
HAITÍ                                1
Name: count, Length: 90, dtype: int64

====================================
VARIABLE: Recuperado
====================================
Recuperado
Recuperado    6208573
Fallecido      142830
NaN             36327
Activo           2946
fallecido         295
Name: count, dtype: int64

====================================
VARIABLE: Fecha de inicio de síntomas
====================================
Fecha de inicio de síntomas
NaN                    505384
2022-01-03 00:00:00     41484
2022-01-04 00:00:00     36705
2022-01-02 00:00:00     32899
2021-06-15 00:00:00     30647
                        ...
2020-03-03 00:00:00         2
2020-02-28 00:00:00         2
2020-02-29 00:00:00         2
2024-01-15 00:00:00         1
2020-02-27 00:00:00         1
Name: count, Length: 1420, dtype: int64

====================================
VARIABLE: Fecha de muerte
====================================
Fecha de muerte
NaN                    6206578
2021-06-21 00:00:00        716
2021-06-24 00:00:00        694
2021-06-20 00:00:00        684
2021-06-23 00:00:00        682
                        ...
2023-08-25 00:00:00          1
2023-09-16 00:00:00          1
2023-11-05 00:00:00          1
2023-09-19 00:00:00          1
2023-10-13 00:00:00          1
Name: count, Length: 1392, dtype: int64

====================================
VARIABLE: Fecha de diagnóstico
====================================
Fecha de diagnóstico
2022-01-07 00:00:00    42180
2022-01-06 00:00:00    40352
2022-01-12 00:00:00    35609
2022-01-05 00:00:00    35551
2022-01-11 00:00:00    35495
                       ...
2020-03-12 00:00:00        4
2020-03-09 00:00:00        2
2020-10-07 00:00:01        1
2024-01-16 00:00:00        1
2020-03-06 00:00:00        1
Name: count, Length: 1411, dtype: int64

====================================
VARIABLE: Fecha de recuperación
====================================
Fecha de recuperación
NaN                    182324
2021-06-15 00:00:00     61040
2021-06-17 00:00:00     51467
2021-06-01 00:00:00     40608
2021-07-06 00:00:00     38658
                        ...
2022-05-01 00:00:00         1
2020-03-14 00:00:00         1
2023-08-26 00:00:00         1
2022-12-23 00:00:00         1
2022-09-30 00:00:00         1
Name: count, Length: 970, dtype: int64

====================================
VARIABLE: Tipo de recuperación
====================================
Tipo de recuperación
Tiempo    5274348
PCR        933773
NaN        182398
TIEMPO        452
Name: count, dtype: int64

====================================
VARIABLE: Nombre del grupo étnico
====================================
Nombre del grupo étnico
NaN                            6307107
Por definir                      17222
Sin Comunidad                    12064
ZENU                              9264
PIJAO                             4112
                                ...
MESAS DE SAN JUAN                    1
YORROLOKI                            1
GEMEMAHS-KURAPULEN-JUYUMANA          1
ISHORSHIMANA                         1
TUTCHONKAT                           1
Name: count, Length: 1888, dtype: int64

In [15]:
resumen = pd.DataFrame({
    'Variable': data.columns,
    'Tipo de dato': data.dtypes.astype(str).values,
    'Valores no nulos': data.notnull().sum().values,
    'Valores faltantes': data.isnull().sum().values,
    'Valores únicos': [
        data[col].nunique(dropna=False) for col in data.columns
    ]
})

resumen

,Variable,Tipo de dato,Valores no nulos,Valores faltantes,Valores únicos
0,fecha reporte web,object,6390971,0,872
1,ID de caso,object,6390971,0,6390971
2,Fecha de notificación,object,6390971,0,1413
3,Código DIVIPOLA departamento,object,6390971,0,36
4,Nombre departamento,object,6390971,0,41
5,Código DIVIPOLA municipio,object,6390971,0,1121
6,Nombre municipio,object,6390971,0,1057
7,Edad,int64,6390971,0,114
8,Unidad de medida de edad,int64,6390971,0,5
9,Sexo,object,6390971,0,4
10,Tipo de contagio,object,6390971,0,3
11,Ubicación del caso,object,6349703,41268,7
12,Estado,object,6349703,41268,7
13,Código ISO del país,object,3710,6387261,122
14,Nombre del país,object,3718,6387253,90
15,Recuperado,object,6354644,36327,5
16,Fecha de inicio de síntomas,object,5885587,505384,1420
17,Fecha de muerte,object,184393,6206578,1392
18,Fecha de diagnóstico,object,6388216,2755,1411
19,Fecha de recuperación,object,6208647,182324,970
20,Tipo de recuperación,object,6208573,182398,4
21,Pertenencia étnica,float64,6388815,2156,6
22,Nombre del grupo étnico,object,83864,6307107,1888

Conclusion

- El análisis descriptivo realizado sobre el conjunto de datos de casos de COVID-19 en Colombia permitió conocer las principales características de las variables y la forma en que se distribuyen los registros. Se encontraron variables de diferentes naturalezas: cuantitativas, como la edad y los identificadores numéricos, cualitativas, como sexo, estado, atención, tipo, departamento y pertenencia étnica, y variables relacionadas con fechas, como la fecha de notificación, diagnóstico, recuperación y muerte.

EJERCICIO 3

Crear una muestra de 50.000 registros

In [19]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.1.3)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (4.6.0)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.61.2)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.13/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 6.5 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 23.9 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 50.2 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (682 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 38.1 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 9.3 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.1 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.4

In [20]:
from ydata_profiling import ProfileReport

/tmp/ipykernel_4830/44057814.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [22]:
# Crear una muestra de 50.000 registros
data_muestra = data.sample(
    n=min(50000, len(data)),
    random_state=42
)

In [23]:
profile = ProfileReport(
    data_muestra,
    title="Perfilado de datos - COVID-19 en Colombia",
    explorative=True
)

profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/23 [00:00<?, ?it/s]
  4%|▍         | 1/23 [00:00<00:19,  1.12it/s]
  9%|▊         | 2/23 [00:02<00:20,  1.03it/s]
 13%|█▎        | 3/23 [00:02<00:11,  1.72it/s]
 17%|█▋        | 4/23 [00:02<00:07,  2.44it/s]
 22%|██▏       | 5/23 [00:02<00:06,  2.90it/s]
 26%|██▌       | 6/23 [00:02<00:05,  3.22it/s]
 35%|███▍      | 8/23 [00:02<00:03,  4.94it/s]
 39%|███▉      | 9/23 [00:02<00:02,  5.50it/s]
 43%|████▎     | 10/23 [00:03<00:02,  5.33it/s]
 52%|█████▏    | 12/23 [00:03<00:02,  4.64it/s]
 57%|█████▋    | 13/23 [00:03<00:01,  5.30it/s]
 65%|██████▌   | 15/23 [00:04<00:01,  5.68it/s]
 70%|██████▉   | 16/23 [00:04<00:01,  5.28it/s]
 74%|███████▍  | 17/23 [00:04<00:01,  4.28it/s]
 83%|████████▎ | 19/23 [00:05<00:00,  4.71it/s]
 87%|████████▋ | 20/23 [00:05<00:00,  5.16it/s]
 91%|█████████▏| 21/23 [00:05<00:00,  4.39it/s]
100%|██████████| 23/23 [00:05<00:00,  4.09it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

CONCLUSIONES

- El perfilado realizado al conjunto de datos de COVID-19 en Colombia permitió identificar diferentes características y posibles anomalías relacionadas con la calidad de los datos. En primer lugar, se encontraron valores faltantes en varias variables. Estos valores no necesariamente representan errores, ya que algunas variables dependen de la evolución del caso. Por ejemplo, las fechas de muerte o recuperación pueden no estar registradas cuando el evento no ocurrió o no fue reportado.

- Finalmente, el perfilado permite concluir que, aunque el conjunto de datos contiene información suficiente para realizar análisis descriptivos y estadísticos, es necesario realizar previamente un proceso de limpieza y validación de los datos. Las principales situaciones que deben tenerse en cuenta son los valores faltantes, posibles duplicados, valores atípicos, inconsistencias en variables categóricas y posibles errores en las fechas. Estas anomalías deben ser documentadas y tratadas cuidadosamente para evitar modificar información válida y garantizar que los análisis posteriores sean confiables.